"""add mastered_at to knowledge_points

Revision ID: 42c2b09275b5
Revises: b6bd40d13b65
Create Date: 2026-04-02 22:18:58.701050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c2b09275b5'
down_revision: Union[str, None] = 'b6bd40d13b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_points', sa.Column('mastered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_points', 'mastered_at')
    # ### end Alembic commands ###
