"""add illustration cache to knowledge_points

Revision ID: a979c0f6db30
Revises: 28052b383f13
Create Date: 2026-04-02 18:44:48.450382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a979c0f6db30'
down_revision: Union[str, None] = '28052b383f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_points', sa.Column('illustration', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_points', 'illustration')
    # ### end Alembic commands ###
