"""add question cache to knowledge_points

Revision ID: b6bd40d13b65
Revises: a979c0f6db30
Create Date: 2026-04-02 22:00:51.879942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bd40d13b65'
down_revision: Union[str, None] = 'a979c0f6db30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_points', sa.Column('question', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_points', 'question')
    # ### end Alembic commands ###
