from manim import *
import numpy as np


class FluidFlowStreamlineExample(Scene):
    """
    Incompressible 2D flow around a unit cylinder: u = U_∞(1 - R²/r² cos(2θ)),
    visualized via tracer particles riding streamlines.

    SINGLE_FOCUS:
      Cylinder at origin; streamline sketches drawn; ValueTracker
      t_tr advances 24 tracer particle positions along streamlines
      via always_redraw. Particles split around the cylinder and
      reconverge downstream.
    """

    def construct(self):
        title = Tex(r"Streamline flow past a cylinder",
                    font_size=28).to_edge(UP, buff=0.3)
        self.play(Write(title))

        cyl = Circle(radius=0.8, color=WHITE, fill_opacity=0.9,
                      fill_color=GREY_B).move_to([0, 0, 0])
        self.play(Create(cyl))

        # Draw a few streamlines as static guides
        def velocity(x, y):
            r2 = x * x + y * y
            if r2 < 0.66:
                return np.array([0.0, 0.0])
            R2 = 0.64
            ux = 1 - R2 * (x * x - y * y) / (r2 * r2)
            uy = -2 * R2 * x * y / (r2 * r2)
            return np.array([ux, uy])

        # Streamlines generated by forward-integrating from left edge
        streamlines = VGroup()
        for y0 in np.linspace(-2.6, 2.6, 13):
            if abs(y0) < 0.85:
                continue
            pts = [np.array([-6.0, y0, 0])]
            pos = np.array([-6.0, y0])
            for _ in range(600):
                v = velocity(pos[0], pos[1])
                vmag = np.linalg.norm(v)
                if vmag < 1e-4:
                    break
                pos = pos + 0.025 * v / (vmag + 1e-8)
                if pos[0] > 6.0:
                    break
                if (pos[0] ** 2 + pos[1] ** 2) < 0.66:
                    break
                pts.append(np.array([pos[0], pos[1], 0]))
            v_mob = VMobject(color=BLUE_D, stroke_width=1.8,
                              stroke_opacity=0.45)
            if len(pts) >= 2:
                v_mob.set_points_as_corners(pts)
            streamlines.add(v_mob)
        self.play(Create(streamlines), run_time=2)

        # Tracer particles each with own y0 seed
        N_particles = 20
        seeds = np.linspace(-2.4, 2.4, N_particles)
        # pre-integrate long trajectories per seed
        trajs = []
        for y0 in seeds:
            if abs(y0) < 0.85:
                # deflected seed: start a bit offset
                y0 = y0 * 1.4
            pts = []
            pos = np.array([-6.0, y0])
            for _ in range(800):
                v = velocity(pos[0], pos[1])
                vmag = np.linalg.norm(v)
                if vmag < 1e-4:
                    pts.append(pts[-1] if pts else np.array([-6, y0, 0]))
                    continue
                pos = pos + 0.02 * v / (vmag + 1e-8)
                if pos[0] > 6.0:
                    break
                if (pos[0] ** 2 + pos[1] ** 2) < 0.66:
                    # nudge along tangent to avoid entering cylinder
                    pos += 0.02 * np.array([-pos[1], pos[0]]) / (np.linalg.norm(pos) + 1e-8)
                pts.append(np.array([pos[0], pos[1], 0]))
            trajs.append(pts)

        max_len = max(len(t) for t in trajs)
        t_tr = ValueTracker(0.0)

        def tracers():
            grp = VGroup()
            tnow = t_tr.get_value()
            for i, traj in enumerate(trajs):
                idx = int(tnow * (len(traj) - 1))
                idx = max(0, min(idx, len(traj) - 1))
                grp.add(Dot(traj[idx], color=YELLOW, radius=0.08))
            return grp

        self.add(always_redraw(tracers))

        self.play(t_tr.animate.set_value(1.0),
                   run_time=10, rate_func=linear)
        self.wait(0.5)
