from manim import *
import numpy as np


class PellEquationExample(Scene):
    """
    Pell equation x² − 61 y² = 1. Fundamental solution is huge:
    (x, y) = (1766319049, 226153980). Smaller solutions generated
    recursively.

    Use D=7 for visual tractability: x² − 7y² = 1 has fundamental
    (8, 3) and solutions generated by (x + y√7) = (8 + 3√7)^k.

    TWO_COLUMN: LEFT plots the hyperbola x² − 7y² = 1 (blue branches);
    ValueTracker k_tr steps k=1..5; always_redraw places current
    (x_k, y_k) RED dot. RIGHT shows recursion p_k=8 p_{k-1}+21 q_{k-1}
    and live (x_k, y_k, y_k/x_k → 1/√7).
    """

    def construct(self):
        title = Tex(r"Pell: $x^2-7y^2=1$",
                    font_size=30).to_edge(UP, buff=0.3)
        self.play(Write(title))

        # Solutions
        x_list = [1]
        y_list = [0]
        x, y = 8, 3
        for _ in range(5):
            x_list.append(x)
            y_list.append(y)
            x_new = 8 * x + 21 * y
            y_new = 3 * x + 8 * y
            x, y = x_new, y_new

        axes = Axes(x_range=[-1, 280, 50], y_range=[-1, 110, 20],
                    x_length=6.0, y_length=4.0,
                    axis_config={"include_numbers": True,
                                 "font_size": 16}).shift(LEFT * 2.3 + DOWN * 0.3)
        self.play(Create(axes))

        # Hyperbola branches
        def hyp_plus(x):
            return np.sqrt(max(0, (x ** 2 - 1) / 7))

        hyp = axes.plot(hyp_plus, x_range=[1, 270], color=BLUE, stroke_width=2)
        self.play(Create(hyp))

        k_tr = ValueTracker(1.0)

        def dot():
            k = int(round(k_tr.get_value()))
            k = max(1, min(len(x_list) - 1, k))
            return Dot(axes.c2p(x_list[k], y_list[k]),
                        color=RED, radius=0.1)

        def trail():
            k = int(round(k_tr.get_value()))
            k = max(1, min(len(x_list) - 1, k))
            pts = [axes.c2p(x_list[i], y_list[i]) for i in range(1, k + 1)]
            g = VGroup()
            for p in pts:
                g.add(Dot(p, color=YELLOW, radius=0.06))
            return g

        self.add(always_redraw(dot), always_redraw(trail))

        # Right column
        def k_now():
            return max(1, min(len(x_list) - 1, int(round(k_tr.get_value()))))

        info = VGroup(
            Tex(r"$(x_{k+1}, y_{k+1}) = (8x_k+21y_k,\ 3x_k+8y_k)$", font_size=20),
            VGroup(Tex(r"$k=$", font_size=22),
                   DecimalNumber(1, num_decimal_places=0,
                                 font_size=22).set_color(RED)).arrange(RIGHT, buff=0.1),
            VGroup(Tex(r"$x_k=$", font_size=22),
                   DecimalNumber(8, num_decimal_places=0,
                                 font_size=22).set_color(RED)).arrange(RIGHT, buff=0.1),
            VGroup(Tex(r"$y_k=$", font_size=22),
                   DecimalNumber(3, num_decimal_places=0,
                                 font_size=22).set_color(RED)).arrange(RIGHT, buff=0.1),
            VGroup(Tex(r"$x_k^2-7y_k^2=$", font_size=22),
                   DecimalNumber(1, num_decimal_places=0,
                                 font_size=22).set_color(GREEN)).arrange(RIGHT, buff=0.1),
            VGroup(Tex(r"$y_k/x_k=$", font_size=22),
                   DecimalNumber(0.375, num_decimal_places=6,
                                 font_size=22).set_color(YELLOW)).arrange(RIGHT, buff=0.1),
            Tex(r"$1/\sqrt{7}\approx 0.377964$", color=YELLOW, font_size=20),
        ).arrange(DOWN, aligned_edge=LEFT, buff=0.2).to_edge(RIGHT, buff=0.2)

        info[1][1].add_updater(lambda m: m.set_value(k_now()))
        info[2][1].add_updater(lambda m: m.set_value(x_list[k_now()]))
        info[3][1].add_updater(lambda m: m.set_value(y_list[k_now()]))
        info[4][1].add_updater(lambda m: m.set_value(
            x_list[k_now()] ** 2 - 7 * y_list[k_now()] ** 2))
        info[5][1].add_updater(lambda m: m.set_value(
            y_list[k_now()] / x_list[k_now()] if x_list[k_now()] else 0))
        self.add(info)

        for k in [2, 3, 4, 5]:
            self.play(k_tr.animate.set_value(float(k)),
                      run_time=1.5, rate_func=smooth)
            self.wait(0.4)
        self.wait(0.8)
